import Menu from "./Menu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
         <Menu/>
        {children}
       
       </body>
    </html>
  )
}
